/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlumnoRouteImport } from './routes/alumno'
import { Route as AlumnosRouteImport } from './routes/alumnos'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ClasesRouteImport } from './routes/clases'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as InformesRouteImport } from './routes/informes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfesoresRouteImport } from './routes/profesores'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as AlumnosStudentIdRouteImport } from './routes/alumnos.$studentId'
import { Route as ClasesClassIdRouteImport } from './routes/clases.$classId'
import { Route as ProfesoresTeacherIdRouteImport } from './routes/profesores.$teacherId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnoRoute = AlumnoRouteImport.update({
  id: '/alumno',
  path: '/alumno',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnosRoute = AlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesRoute = ClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const InformesRoute = InformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesoresRoute = ProfesoresRouteImport.update({
  id: '/profesores',
  path: '/profesores',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumnosStudentIdRoute = AlumnosStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AlumnosRoute,
} as any)
const ClasesClassIdRoute = ClasesClassIdRouteImport.update({
  id: '/$classId',
  path: '/$classId',
  getParentRoute: () => ClasesRoute,
} as any)
const ProfesoresTeacherIdRoute = ProfesoresTeacherIdRouteImport.update({
  id: '/$teacherId',
  path: '/$teacherId',
  getParentRoute: () => ProfesoresRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRoute
  '/alumnos': typeof AlumnosRouteWithChildren
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/clases': typeof ClasesRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/informes': typeof InformesRoute
  '/login': typeof LoginRoute
  '/profesores': typeof ProfesoresRouteWithChildren
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/alumnos/$studentId': typeof AlumnosStudentIdRoute
  '/clases/$classId': typeof ClasesClassIdRoute
  '/profesores/$teacherId': typeof ProfesoresTeacherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRoute
  '/alumnos': typeof AlumnosRouteWithChildren
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/clases': typeof ClasesRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/informes': typeof InformesRoute
  '/login': typeof LoginRoute
  '/profesores': typeof ProfesoresRouteWithChildren
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/alumnos/$studentId': typeof AlumnosStudentIdRoute
  '/clases/$classId': typeof ClasesClassIdRoute
  '/profesores/$teacherId': typeof ProfesoresTeacherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alumno': typeof AlumnoRoute
  '/alumnos': typeof AlumnosRouteWithChildren
  '/biblioteca': typeof BibliotecaRoute
  '/calendario': typeof CalendarioRoute
  '/clases': typeof ClasesRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/informes': typeof InformesRoute
  '/login': typeof LoginRoute
  '/profesores': typeof ProfesoresRouteWithChildren
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/alumnos/$studentId': typeof AlumnosStudentIdRoute
  '/clases/$classId': typeof ClasesClassIdRoute
  '/profesores/$teacherId': typeof ProfesoresTeacherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alumno'
    | '/alumnos'
    | '/biblioteca'
    | '/calendario'
    | '/clases'
    | '/configuracion'
    | '/informes'
    | '/login'
    | '/profesores'
    | '/recuperar-contrasena'
    | '/registro'
    | '/alumnos/$studentId'
    | '/clases/$classId'
    | '/profesores/$teacherId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alumno'
    | '/alumnos'
    | '/biblioteca'
    | '/calendario'
    | '/clases'
    | '/configuracion'
    | '/informes'
    | '/login'
    | '/profesores'
    | '/recuperar-contrasena'
    | '/registro'
    | '/alumnos/$studentId'
    | '/clases/$classId'
    | '/profesores/$teacherId'
  id:
    | '__root__'
    | '/'
    | '/alumno'
    | '/alumnos'
    | '/biblioteca'
    | '/calendario'
    | '/clases'
    | '/configuracion'
    | '/informes'
    | '/login'
    | '/profesores'
    | '/recuperar-contrasena'
    | '/registro'
    | '/alumnos/$studentId'
    | '/clases/$classId'
    | '/profesores/$teacherId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlumnoRoute: typeof AlumnoRoute
  AlumnosRoute: typeof AlumnosRouteWithChildren
  BibliotecaRoute: typeof BibliotecaRoute
  CalendarioRoute: typeof CalendarioRoute
  ClasesRoute: typeof ClasesRouteWithChildren
  ConfiguracionRoute: typeof ConfiguracionRoute
  InformesRoute: typeof InformesRoute
  LoginRoute: typeof LoginRoute
  ProfesoresRoute: typeof ProfesoresRouteWithChildren
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumno': {
      id: '/alumno'
      path: '/alumno'
      fullPath: '/alumno'
      preLoaderRoute: typeof AlumnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnos': {
      id: '/alumnos'
      path: '/alumnos'
      fullPath: '/alumnos'
      preLoaderRoute: typeof AlumnosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clases': {
      id: '/clases'
      path: '/clases'
      fullPath: '/clases'
      preLoaderRoute: typeof ClasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informes': {
      id: '/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof InformesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesores': {
      id: '/profesores'
      path: '/profesores'
      fullPath: '/profesores'
      preLoaderRoute: typeof ProfesoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumnos/$studentId': {
      id: '/alumnos/$studentId'
      path: '/$studentId'
      fullPath: '/alumnos/$studentId'
      preLoaderRoute: typeof AlumnosStudentIdRouteImport
      parentRoute: typeof AlumnosRoute
    }
    '/clases/$classId': {
      id: '/clases/$classId'
      path: '/$classId'
      fullPath: '/clases/$classId'
      preLoaderRoute: typeof ClasesClassIdRouteImport
      parentRoute: typeof ClasesRoute
    }
    '/profesores/$teacherId': {
      id: '/profesores/$teacherId'
      path: '/$teacherId'
      fullPath: '/profesores/$teacherId'
      preLoaderRoute: typeof ProfesoresTeacherIdRouteImport
      parentRoute: typeof ProfesoresRoute
    }
  }
}

interface AlumnosRouteChildren {
  AlumnosStudentIdRoute: typeof AlumnosStudentIdRoute
}

const AlumnosRouteChildren: AlumnosRouteChildren = {
  AlumnosStudentIdRoute: AlumnosStudentIdRoute,
}

const AlumnosRouteWithChildren =
  AlumnosRoute._addFileChildren(AlumnosRouteChildren)

interface ClasesRouteChildren {
  ClasesClassIdRoute: typeof ClasesClassIdRoute
}

const ClasesRouteChildren: ClasesRouteChildren = {
  ClasesClassIdRoute: ClasesClassIdRoute,
}

const ClasesRouteWithChildren =
  ClasesRoute._addFileChildren(ClasesRouteChildren)

interface ProfesoresRouteChildren {
  ProfesoresTeacherIdRoute: typeof ProfesoresTeacherIdRoute
}

const ProfesoresRouteChildren: ProfesoresRouteChildren = {
  ProfesoresTeacherIdRoute: ProfesoresTeacherIdRoute,
}

const ProfesoresRouteWithChildren = ProfesoresRoute._addFileChildren(
  ProfesoresRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlumnoRoute: AlumnoRoute,
  AlumnosRoute: AlumnosRouteWithChildren,
  BibliotecaRoute: BibliotecaRoute,
  CalendarioRoute: CalendarioRoute,
  ClasesRoute: ClasesRouteWithChildren,
  ConfiguracionRoute: ConfiguracionRoute,
  InformesRoute: InformesRoute,
  LoginRoute: LoginRoute,
  ProfesoresRoute: ProfesoresRouteWithChildren,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
